// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Areas.Users.DTO;

public partial class CompleteProfileRequestDTO
{
    public class AdminDashboardOverviewDto
    {
        public DashboardSummaryDto Dashboard { get; set; } = new();
        public List<MonthlyRevenueDto> YearlyRevenue { get; set; } = new();
    }

    public class DashboardSummaryDto
    {
        public int TotalMembers { get; set; }
        public decimal YearlyRevenue { get; set; }
        public int MonthOrders { get; set; }
        public decimal AvgOrderAmount { get; set; }
    }

    public class MonthlyRevenueDto
    {
        public int Month { get; set; }
        public decimal Amount { get; set; }
    }

}

