// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Areas.Users.DTO;

public partial class CompleteProfileRequestDTO
{
    public string Phone { get; set; }
    public string Address { get; set; }
    public string ShippingAddress { get; set; }
    public DateTime BirthDay { get; set; }
}