// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Areas.Users.DTO;

public class EmailDTO
{
    public string Mail { get; set; }
    public class SendVerifyEmailDto
    {
        public string FrontendUrl { get; set; } = "";
    }
    public class UpdateEmailDto
    {
        public string NewEmail { get; set; } = "";
        public string FrontendUrl { get; set; } = "";
    }

    public class EmailChangeCache //存一個Cache搭配UpdateEmail用
    {
        public int UserId { get; set; }
        public string NewEmail { get; set; } = null!;
    }

}

