// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Areas.Users.DTO;

public class EmailDTO
{

    public string Mail { get; set; }



}

