// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Areas.Users.DTO;

public class LoginDTO
{

    public string Mail { get; set; }

    public string Password { get; set; }


}

public class AuthResponseDTO
{
    public string Token { get; set; }
    public string Message { get; set; }
    public AuthUserDTO User { get; set; }
}

public class AuthUserDTO
{
    public int UserId { get; set; }
    public string Mail { get; set; }
    public string FullName { get; set; }
    public string ImageUrl { get; set; }
    public bool ProfileCompleted { get; set; }
    public string Provider { get; set; }
}
