// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PcShop.Areas.Users.Data;
using System;
using System.Collections.Generic;

namespace PcShop.Areas.Users.DTO;

public class OrderListDTO
{
    public int OrderId { get; set; }
    public string OrderNo { get; set; } = null!;
    public DateTime CreateDate { get; set; }
    public decimal TotalAmount { get; set; }
    public OrderStatus Status { get; set; }

}
public class OrderDetailsDTO
{
    public int OrderId { get; set; }
    public string OrderNo { get; set; } = null!;
    public string Status { get; set; } = null!;
    public DateTime CreateDate { get; set; }
    public decimal TotalAmount { get; set; }

    public List<OrderItemDto> Items { get; set; } = new();
}
public class OrderItemDto
{
    public string ProductName { get; set; } = null!;

    public string ProductImage { get;set; } = null!;
    public int Quantity { get; set; }
    public decimal UnitPriceAtPurchase { get; set; }
    public decimal SubTotal => Quantity * UnitPriceAtPurchase;
}
