// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Ad
{
    public int AdId { get; set; }

    public string Title { get; set; }

    public string MediaUrl { get; set; }

    public string LinkUrl { get; set; }

    public int? PositionId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<AdsReport> AdsReports { get; set; } = new List<AdsReport>();

    public virtual Position Position { get; set; }
}