// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class AdsReport
{
    public int StatId { get; set; }

    public int AdId { get; set; }

    public int Clicks { get; set; }

    public DateOnly Date { get; set; }

    public int? PositionId { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public virtual Ad Ad { get; set; }
}