// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class BrowsingHistory
{
    public int BrowsingHistoryId { get; set; }

    public int UserId { get; set; }

    public int? ProductId { get; set; }

    public string Url { get; set; }

    public DateTime VisitTime { get; set; }

    public virtual Product Product { get; set; }

    public virtual UserProfile User { get; set; }
}