// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Cart
{
    /// <summary>
    /// 購物車ID
    /// </summary>
    public int CartId { get; set; }

    /// <summary>
    /// 所屬用戶ID (未登入訪客為 NULL)
    /// </summary>
    public int? UserId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後修改時間
    /// </summary>
    public DateTime LastModifiedAt { get; set; }

    /// <summary>
    /// GUID-用來辨識未登入者
    /// </summary>
    public Guid SessionKey { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual UserProfile User { get; set; }
}