// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string CouponCode { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public decimal MinOrderAmount { get; set; }

    public int MaxUses { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<UserCoupon> UserCoupons { get; set; } = new List<UserCoupon>();
}