// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PcShop.Models;

public partial class ExamContext : DbContext
{
    public ExamContext(DbContextOptions<ExamContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ad> Ads { get; set; }

    public virtual DbSet<AdsReport> AdsReports { get; set; }

    public virtual DbSet<BrowsingHistory> BrowsingHistories { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<Faq> Faqs { get; set; }

    public virtual DbSet<Faqblock> Faqblocks { get; set; }

    public virtual DbSet<Faqcategory> Faqcategories { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<Game> Games { get; set; }

    public virtual DbSet<GamePoint> GamePoints { get; set; }

    public virtual DbSet<LoginHistory> LoginHistories { get; set; }

    public virtual DbSet<MemberLevel> MemberLevels { get; set; }

    public virtual DbSet<Oauth> Oauths { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<PaymentLogsEcpay> PaymentLogsEcpays { get; set; }

    public virtual DbSet<PaymentLogsLinePay> PaymentLogsLinePays { get; set; }

    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }

    public virtual DbSet<PointHistory> PointHistories { get; set; }

    public virtual DbSet<Position> Positions { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductReport> ProductReports { get; set; }

    public virtual DbSet<ProductReview> ProductReviews { get; set; }

    public virtual DbSet<ProductSku> ProductSkus { get; set; }

    public virtual DbSet<Record> Records { get; set; }

    public virtual DbSet<UserCoupon> UserCoupons { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<UserQuestion> UserQuestions { get; set; }

    public virtual DbSet<UsersBlackList> UsersBlackLists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Ad>(entity =>
        {
            entity.HasKey(e => e.AdId).HasName("PK__Ads__7130D5AEEC3D3D26");

            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.LinkUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.MediaUrl)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PositionId).HasColumnName("PositionID");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Position).WithMany(p => p.Ads)
                .HasForeignKey(d => d.PositionId)
                .HasConstraintName("FK_Ads_Position");
        });

        modelBuilder.Entity<AdsReport>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__AdsRepor__3A162D3E178B8316");

            entity.ToTable("AdsReport");

            entity.HasOne(d => d.Ad).WithMany(p => p.AdsReports)
                .HasForeignKey(d => d.AdId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdsReport_Ads");
        });

        modelBuilder.Entity<BrowsingHistory>(entity =>
        {
            entity.HasKey(e => e.BrowsingHistoryId).HasName("PK__Browsing__D37AB25282261CCF");

            entity.ToTable("BrowsingHistory");

            entity.Property(e => e.BrowsingHistoryId).HasColumnName("BrowsingHistoryID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("URL");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VisitTime)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__BrowsingH__Visit__481BA567");

            entity.HasOne(d => d.Product).WithMany(p => p.BrowsingHistories)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_Browsing_Product");

            entity.HasOne(d => d.User).WithMany(p => p.BrowsingHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Browsing_User");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Carts__51BCD797E625D43C");

            entity.Property(e => e.CartId)
                .HasComment("購物車ID")
                .HasColumnName("CartID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasComment("建立時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Carts__CreatedAt__697C9932")
                .HasColumnType("datetime");
            entity.Property(e => e.LastModifiedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasComment("最後修改時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Carts__LastModif__6A70BD6B")
                .HasColumnType("datetime");
            entity.Property(e => e.SessionKey)
                .HasDefaultValueSql("(newid())")
                .HasComment("GUID-用來辨識未登入者")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Carts_SessionKey");
            entity.Property(e => e.UserId)
                .HasComment("所屬用戶ID (未登入訪客為 NULL)")
                .HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Carts)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Cart_User");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.CartItemId).HasName("PK__CartItem__488B0B2A4D1195C2");

            entity.Property(e => e.CartItemId)
                .HasComment("購物車項目ID")
                .HasColumnName("CartItemID");
            entity.Property(e => e.CartId)
                .HasComment("所屬購物車ID")
                .HasColumnName("CartID");
            entity.Property(e => e.Quantity).HasComment("項目數量");
            entity.Property(e => e.Skuid)
                .HasComment("商品規格ID")
                .HasColumnName("SKUID");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.CartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartItems_Cart");

            entity.HasOne(d => d.Sku).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.Skuid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CartItems_SKU");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2B0564CE38");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.CouponId).HasName("PK__Coupons__384AF1DA47477C99");

            entity.Property(e => e.CouponId).HasColumnName("CouponID");
            entity.Property(e => e.CouponCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DiscountType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.DiscountValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinOrderAmount).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Faq>(entity =>
        {
            entity.HasKey(e => e.Faqid).HasName("PK__FAQs__3213E83FBBAC9583");

            entity.ToTable("FAQs");

            entity.Property(e => e.Faqid).HasColumnName("FAQid");
            entity.Property(e => e.Answer)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("answer");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("question");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Category).WithMany(p => p.Faqs)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FAQs_FAQCategory");
        });

        modelBuilder.Entity<Faqblock>(entity =>
        {
            entity.HasKey(e => e.FaqblockId).HasName("PK__FAQBlock__356F41B566BA6B34");

            entity.ToTable("FAQBlocks");

            entity.HasIndex(e => new { e.Faqid, e.SortOrder }, "IX_FAQBlocks_FAQid_SortOrder");

            entity.Property(e => e.FaqblockId).HasColumnName("FAQBlockId");
            entity.Property(e => e.BlockType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_FAQBlocks_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Faqid).HasColumnName("FAQid");
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.SortOrder).HasAnnotation("Relational:DefaultConstraintName", "DF_FAQBlocks_SortOrder");

            entity.HasOne(d => d.Faq).WithMany(p => p.Faqblocks)
                .HasForeignKey(d => d.Faqid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FAQBlocks_FAQs");
        });

        modelBuilder.Entity<Faqcategory>(entity =>
        {
            entity.HasKey(e => e.Faqcategoryid).HasName("PK__Category__3213E83FA4DDF331");

            entity.ToTable("FAQCategory");

            entity.Property(e => e.Faqcategoryid).HasColumnName("FAQCategoryid");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_FAQCategory_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_FAQCategory_IsActive");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.ProductId });

            entity.ToTable("Favorite");

            entity.Property(e => e.UserId)
                .ValueGeneratedOnAdd()
                .HasColumnName("UserID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.AddDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Favorite__AddDat__04308F6E");

            entity.HasOne(d => d.Product).WithMany(p => p.Favorites)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Favorite_Product");

            entity.HasOne(d => d.User).WithMany(p => p.Favorites)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Favorite_User");
        });

        modelBuilder.Entity<Game>(entity =>
        {
            entity.HasKey(e => e.GameId).HasName("PK__Games__2AB897FD948FD13A");

            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.GameName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<GamePoint>(entity =>
        {
            entity.HasKey(e => e.UserPointId).HasName("PK__GamePoin__9F29502E2A4F2EA1");

            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.ObtainedAt).HasColumnType("datetime");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UsedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.GamePoints)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GamePoints_User");
        });

        modelBuilder.Entity<LoginHistory>(entity =>
        {
            entity.HasKey(e => e.LoginHistoryId).HasName("PK__LoginHis__2773EAFF857E0F4D");

            entity.ToTable("LoginHistory");

            entity.Property(e => e.LoginHistoryId).HasColumnName("LoginHistoryID");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(255)
                .HasColumnName("IPAddress");
            entity.Property(e => e.LoginTime).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.LoginHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LoginHistory_User");
        });

        modelBuilder.Entity<MemberLevel>(entity =>
        {
            entity.HasKey(e => e.LevelId).HasName("PK__MemberLe__09F03C06C890B5E3");

            entity.Property(e => e.LevelId).HasColumnName("LevelID");
            entity.Property(e => e.DiscountRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LevelName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LevelPictureUrl)
                .HasMaxLength(255)
                .HasColumnName("LevelPictureURL");
            entity.Property(e => e.MinSpending).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<Oauth>(entity =>
        {
            entity.HasKey(e => e.OauthId).HasName("PK__OAuth__F55548D65E6380BC");

            entity.ToTable("OAuth");

            entity.HasIndex(e => new { e.UserId, e.Provider }, "UQ_OAuth").IsUnique();

            entity.Property(e => e.OauthId).HasColumnName("OAuthID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.LastLoginAt).HasColumnType("datetime");
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderUserId)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("ProviderUserID");
            entity.Property(e => e.TokenExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Oauths)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_OAuth_User");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAFA4EDEFB3");

            entity.HasIndex(e => e.OrderNo, "UQ_OrderNo").IsUnique();

            entity.Property(e => e.OrderId)
                .HasComment("訂單ID")
                .HasColumnName("OrderID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasComment("下單時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Orders__CreateDa__73FA27A5")
                .HasColumnType("datetime");
            entity.Property(e => e.OrderNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("訂單單號");
            entity.Property(e => e.OrderStatus).HasComment("訂單狀態,用數字表示");
            entity.Property(e => e.SelectedGateway)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("選擇的金流");
            entity.Property(e => e.SelectedPayment)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("選擇的付款方式");
            entity.Property(e => e.ShippingAddress)
                .IsRequired()
                .HasMaxLength(500)
                .HasComment("寄送地址");
            entity.Property(e => e.ShippingMethodId)
                .HasComment("配送方式ID")
                .HasColumnName("ShippingMethodID");
            entity.Property(e => e.TotalAmount)
                .HasComment("訂單總金額")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdateDate)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .HasComment("下單用戶ID")
                .HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_User");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PK__OrderIte__57ED06A1AEFF04C9");

            entity.Property(e => e.OrderItemId)
                .HasComment("訂單項目ID")
                .HasColumnName("OrderItemID");
            entity.Property(e => e.OrderId)
                .HasComment("所屬訂單ID")
                .HasColumnName("OrderID");
            entity.Property(e => e.PriceAtPurchase)
                .HasComment("實際購買價格 (含折扣)")
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Quantity).HasComment("購買數量");
            entity.Property(e => e.Skuid)
                .HasComment("購買的商品規格ID")
                .HasColumnName("SKUID");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_Order");

            entity.HasOne(d => d.Sku).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.Skuid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderItems_SKU");
        });

        modelBuilder.Entity<PaymentLogsEcpay>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__PaymentL__5E5499A85D0D9B5D");

            entity.ToTable("PaymentLogs_ECPay");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.BankCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CheckMacValue)
                .IsRequired()
                .HasMaxLength(256)
                .IsUnicode(false);
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PaymentLo__Creat__10966653")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpireDate)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MerchantTradeNo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PaymentType)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.PaymentTypeChargeFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RtnMsg)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.TradeDate).HasColumnType("datetime");
            entity.Property(e => e.TradeNo)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.VAccount)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("vAccount");

            entity.HasOne(d => d.Order).WithMany(p => p.PaymentLogsEcpays)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentLogs_ECPay_Order");
        });

        modelBuilder.Entity<PaymentLogsLinePay>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__PaymentL__5E5499A82B781ABE");

            entity.ToTable("PaymentLogs_LinePay");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.ApiAction)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.ConfirmTime).HasColumnType("datetime");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.RegKey)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RequestTime).HasColumnType("datetime");
            entity.Property(e => e.ReturnCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ReturnMessage).HasMaxLength(200);
            entity.Property(e => e.TransactionId)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Order).WithMany(p => p.PaymentLogsLinePays)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentLogs_LinePay_Order");
        });

        modelBuilder.Entity<PaymentTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__PaymentT__55433A4BE38B8D55");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.Gateway)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.GatewayTradeNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PaymentGatewayResponseId)
                .HasMaxLength(255)
                .HasColumnName("PaymentGatewayResponseID");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TransactionAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TransactionStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TransactionTime)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PaymentTr__Trans__08F5448B")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Order).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_PaymentTransactions_Order");

            entity.HasOne(d => d.User).WithMany(p => p.PaymentTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentTransactions_User");
        });

        modelBuilder.Entity<PointHistory>(entity =>
        {
            entity.HasKey(e => e.PointHistoryId).HasName("PK__PointHis__DBE13EF7685ECC97");

            entity.ToTable("PointHistory");

            entity.Property(e => e.PointHistoryId).HasColumnName("PointHistoryID");
            entity.Property(e => e.PointUsedTime)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__PointHist__Point__300F11AC");
            entity.Property(e => e.Reason).IsRequired();
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.PointHistories)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PointHistory_User");
        });

        modelBuilder.Entity<Position>(entity =>
        {
            entity.HasKey(e => e.PositionId).HasName("PK__Position__60BB9A59A812B04E");

            entity.ToTable("Position");

            entity.Property(e => e.PositionId).HasColumnName("PositionID");
            entity.Property(e => e.Position1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Position");
            entity.Property(e => e.Size)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6ED2250A67F");

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.BasePrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Products__Create__416EA7D8");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Status).HasAnnotation("Relational:DefaultConstraintName", "DF__Products__Status__407A839F");
            entity.Property(e => e.WarrantyInfo).HasMaxLength(100);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Category");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__ProductI__7516F4EC9F76C75B");

            entity.Property(e => e.ImageId).HasColumnName("ImageID");
            entity.Property(e => e.ImageSummary).HasMaxLength(300);
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ProductId).HasColumnName("ProductID");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductImage_Product");
        });

        modelBuilder.Entity<ProductReport>(entity =>
        {
            entity.HasKey(e => e.ProductReportId).HasName("PK__ProductR__3210812E9E39DEF7");

            entity.ToTable("ProductReport");

            entity.Property(e => e.ProductReportId).HasColumnName("ProductReportID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.ReportDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductRe__Repor__64B7E415");
            entity.Property(e => e.ReportReason)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductReports)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductReport_Product");

            entity.HasOne(d => d.User).WithMany(p => p.ProductReports)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductReport_User");
        });

        modelBuilder.Entity<ProductReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__ProductR__74BC79AEEC6F9FB1");

            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.IsApproved)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductRe__IsApp__7E77B618");
            entity.Property(e => e.OrderItemId).HasColumnName("OrderItemID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.ReviewDate)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ProductRe__Revie__7D8391DF");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.OrderItem).WithMany(p => p.ProductReviews)
                .HasForeignKey(d => d.OrderItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_OrderItem");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductReviews)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_Product");

            entity.HasOne(d => d.User).WithMany(p => p.ProductReviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_User");
        });

        modelBuilder.Entity<ProductSku>(entity =>
        {
            entity.HasKey(e => e.Skuid).HasName("PK__ProductS__9AEA1BACF6D7ACB5");

            entity.ToTable("ProductSKUs");

            entity.HasIndex(e => new { e.ProductId, e.Skuname }, "UQ_Product_SKU").IsUnique();

            entity.Property(e => e.Skuid).HasColumnName("SKUID");
            entity.Property(e => e.IsOnSale).HasAnnotation("Relational:DefaultConstraintName", "DF__ProductSK__IsOnS__5E0AE686");
            entity.Property(e => e.PriceAdjustment).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.Skuname)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("SKUName");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSkus)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SKU_Product");
        });

        modelBuilder.Entity<Record>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK__Records__FBDF78E95A5050A5");

            entity.Property(e => e.PlayedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Game).WithMany(p => p.Records)
                .HasForeignKey(d => d.GameId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Records_Game");

            entity.HasOne(d => d.User).WithMany(p => p.Records)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Records_User");
        });

        modelBuilder.Entity<UserCoupon>(entity =>
        {
            entity.HasKey(e => e.UserCouponId).HasName("PK__UserCoup__22994B730957951E");

            entity.HasIndex(e => new { e.UserId, e.CouponId }, "UQ_UserCoupons").IsUnique();

            entity.Property(e => e.UserCouponId).HasColumnName("UserCouponID");
            entity.Property(e => e.CouponId).HasColumnName("CouponID");
            entity.Property(e => e.IsUsed).HasAnnotation("Relational:DefaultConstraintName", "DF__UserCoupo__IsUse__174363E2");
            entity.Property(e => e.UsedDate).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Coupon).WithMany(p => p.UserCoupons)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserCoupons_Coupon");

            entity.HasOne(d => d.User).WithMany(p => p.UserCoupons)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserCoupons_User");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__UserProf__1788CCAC3726BEAC");

            entity.HasIndex(e => e.Phone, "IX_Users_Phone_NotNull")
                .IsUnique()
                .HasFilter("([Phone] IS NOT NULL)");

            entity.HasIndex(e => e.Mail, "UQ__UserProf__2724B2D1CA631880").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__UserProfi__Creat__39CD8610");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Is2Faeverified)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__UserProfi__Is2FA__3BB5CE82")
                .HasColumnName("Is2FAEVerified");
            entity.Property(e => e.IsMailVerified).HasAnnotation("Relational:DefaultConstraintName", "DF__UserProfi__IsMai__3AC1AA49");
            entity.Property(e => e.LevelId)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_UserProfiles_LevelID")
                .HasColumnName("LevelID");
            entity.Property(e => e.Mail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PasswordHash).HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.ProfileCompleted).HasAnnotation("Relational:DefaultConstraintName", "DF__UserProfi__Profi__544C7222");
            entity.Property(e => e.Provider).HasMaxLength(50);
            entity.Property(e => e.Salt).HasMaxLength(150);
            entity.Property(e => e.ShippingAddress).HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasDefaultValue((byte)1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__UserProfi__Statu__3CA9F2BB");
            entity.Property(e => e.TotalSpending).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Level).WithMany(p => p.UserProfiles)
                .HasForeignKey(d => d.LevelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserProfiles_Level");
        });

        modelBuilder.Entity<UserQuestion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_que__3213E83FCAA52040");

            entity.ToTable("user_questions");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Answer)
                .HasColumnType("text")
                .HasColumnName("answer");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.FaqId).HasColumnName("faq_id");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("question");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.UserQuestions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserQuestions_User");
        });

        modelBuilder.Entity<UsersBlackList>(entity =>
        {
            entity.HasKey(e => e.BlacklistId).HasName("PK__UsersBla__AFDBF4386A54686C");

            entity.ToTable("UsersBlackList");

            entity.Property(e => e.BlacklistId).HasColumnName("BlacklistID");
            entity.Property(e => e.BlockedById).HasColumnName("BlockedByID");
            entity.Property(e => e.BlockedTime)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__UsersBlac__Block__4CE05A84");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasDefaultValue((byte)1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__UsersBlac__Statu__4DD47EBD");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.BlockedBy).WithMany(p => p.UsersBlackListBlockedBies)
                .HasForeignKey(d => d.BlockedById)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Black_Admin");

            entity.HasOne(d => d.User).WithMany(p => p.UsersBlackListUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Black_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}