// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Faq
{
    public long Faqid { get; set; }

    public int CategoryId { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Faqcategory Category { get; set; }

    public virtual ICollection<Faqblock> Faqblocks { get; set; } = new List<Faqblock>();
}