// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Faqblock
{
    public long FaqblockId { get; set; }

    public long Faqid { get; set; }

    public string BlockType { get; set; }

    public string Content { get; set; }

    public string ImageUrl { get; set; }

    public int SortOrder { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Faq Faq { get; set; }
}