// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class GamePoint
{
    public int UserPointId { get; set; }

    public int UserId { get; set; }

    public string Source { get; set; }

    public int Points { get; set; }

    public DateTime ObtainedAt { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public byte Status { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual UserProfile User { get; set; }
}