// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Game
{
    public int GameId { get; set; }

    public string GameName { get; set; }

    public string Description { get; set; }

    public string GamePicture { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Record> Records { get; set; } = new List<Record>();
}