// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class LoginHistory
{
    public long LoginHistoryId { get; set; }

    public int UserId { get; set; }

    public string Ipaddress { get; set; }

    public DateTime LoginTime { get; set; }

    public byte PasswordRetryCount { get; set; }

    public string DeviceInfo { get; set; }

    public byte LoginSuccess { get; set; }

    public virtual UserProfile User { get; set; }
}