// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class MemberLevel
{
    public int LevelId { get; set; }

    public string LevelName { get; set; }

    public decimal MinSpending { get; set; }

    public decimal DiscountRate { get; set; }

    public string LevelPictureUrl { get; set; }

    public DateTime? UpdateTime { get; set; }

    public virtual ICollection<UserProfile> UserProfiles { get; set; } = new List<UserProfile>();
}