// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Oauth
{
    public int OauthId { get; set; }

    public int? UserId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? TokenExpiredAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public virtual UserProfile User { get; set; }
}