// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public int ShippingMethodId { get; set; }

    public string OrderNo { get; set; }

    public decimal TotalAmount { get; set; }

    public string ShippingAddress { get; set; }

    public string OrderStatus { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string SelectedGateway { get; set; }

    public string SelectedPayment { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PaymentLogsEcpay> PaymentLogsEcpays { get; set; } = new List<PaymentLogsEcpay>();

    public virtual ICollection<PaymentLogsLinePay> PaymentLogsLinePays { get; set; } = new List<PaymentLogsLinePay>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual UserProfile User { get; set; }
}