// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class PaymentTransaction
{
    public int TransactionId { get; set; }

    public int? OrderId { get; set; }

    public int UserId { get; set; }

    public string PaymentMethod { get; set; }

    public decimal TransactionAmount { get; set; }

    public DateTime TransactionTime { get; set; }

    public string TransactionStatus { get; set; }

    public string PaymentGatewayResponseId { get; set; }

    public string Gateway { get; set; }

    public string GatewayTradeNo { get; set; }

    public virtual Order Order { get; set; }

    public virtual UserProfile User { get; set; }
}