// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class PaymentLogsEcpay
{
    public int LogId { get; set; }

    public int OrderId { get; set; }

    public string MerchantTradeNo { get; set; }

    public int RtnCode { get; set; }

    public string RtnMsg { get; set; }

    public string TradeNo { get; set; }

    public int TradeAmt { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentType { get; set; }

    public decimal? PaymentTypeChargeFee { get; set; }

    public DateTime? TradeDate { get; set; }

    public int SimulatePaid { get; set; }

    public string CheckMacValue { get; set; }

    public string PaymentNo { get; set; }

    public string BankCode { get; set; }

    public string VAccount { get; set; }

    public string ExpireDate { get; set; }

    public string RawData { get; set; }

    public DateTime CreateTime { get; set; }

    public virtual Order Order { get; set; }
}