// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class PaymentLogsLinePay
{
    public int LogId { get; set; }

    public int OrderId { get; set; }

    public string TransactionId { get; set; }

    public string ReturnCode { get; set; }

    public string ReturnMessage { get; set; }

    public int? Amount { get; set; }

    public string RegKey { get; set; }

    public string ApiAction { get; set; }

    public DateTime RequestTime { get; set; }

    public DateTime? ConfirmTime { get; set; }

    public string RawData { get; set; }

    public virtual Order Order { get; set; }
}