// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class PointHistory
{
    public int PointHistoryId { get; set; }

    public int UserId { get; set; }

    public int ChangeAmount { get; set; }

    public string Reason { get; set; }

    public DateTime PointUsedTime { get; set; }

    public int BalanceAfter { get; set; }

    public virtual UserProfile User { get; set; }
}