// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Position
{
    public int PositionId { get; set; }

    public string Code { get; set; }

    public string Size { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Ad> Ads { get; set; } = new List<Ad>();
}