// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class ProductSku
{
    public int Skuid { get; set; }

    public int ProductId { get; set; }

    public string Skuname { get; set; }

    public int StockQuantity { get; set; }

    public bool IsOnSale { get; set; }

    public decimal PriceAdjustment { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Product Product { get; set; }
}