// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class ProductReview
{
    public int ReviewId { get; set; }

    public int ProductId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime ReviewDate { get; set; }

    public int OrderItemId { get; set; }

    public bool IsApproved { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual Product Product { get; set; }

    public virtual UserProfile User { get; set; }
}