// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class ProductImage
{
    public int ImageId { get; set; }

    public int ProductId { get; set; }

    public string ImageUrl { get; set; }

    public string ImageSummary { get; set; }

    public int? IsMainOrNot { get; set; }

    public int? ImageSortBy { get; set; }

    public virtual Product Product { get; set; }
}