// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class ProductReport
{
    public int ProductReportId { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public string StatusName { get; set; }

    public string ReportReason { get; set; }

    public DateTime ReportDate { get; set; }

    public virtual Product Product { get; set; }

    public virtual UserProfile User { get; set; }
}