// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PcShop.Domains.Enums;
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class Record
{
    public int RecordId { get; set; }

    public int UserId { get; set; }

    public int GameId { get; set; }

    public int Score { get; set; }

    public DateTime PlayedAt { get; set; }

    public virtual Game Game { get; set; }

    public virtual UserProfile User { get; set; }
}