// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class ShippingMethod
{
    public int ShippingMethodId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string LogisticsType { get; set; }

    public string LogisticsSubType { get; set; }
}