// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class UsersBlackList
{
    public int BlacklistId { get; set; }

    public int UserId { get; set; }

    public int BlockedById { get; set; }

    public DateTime BlockedTime { get; set; }

    public string Reason { get; set; }

    public DateTime? UnBlockedTime { get; set; }

    public byte? Status { get; set; }

    public virtual UserProfile BlockedBy { get; set; }

    public virtual UserProfile User { get; set; }
}