// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class UserCoupon
{
    public int UserCouponId { get; set; }

    public int UserId { get; set; }

    public int CouponId { get; set; }

    public bool IsUsed { get; set; }

    public DateTime? UsedDate { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual UserProfile User { get; set; }
}