// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class UserQuestion
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public long? FaqId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Faq Faq { get; set; }

    public virtual UserProfile User { get; set; }
}