// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PcShop.Models;

public partial class UserProfile
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string ShippingAddress { get; set; }

    public DateTime BirthDay { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreateTime { get; set; }

    public string PasswordHash { get; set; }

    public string Mail { get; set; }

    public byte IsMailVerified { get; set; }

    public DateTime? IsMailVerifiedTime { get; set; }

    public byte Is2Faeverified { get; set; }

    public int LevelId { get; set; }

    public byte Status { get; set; }

    public DateTime? UpdateTime { get; set; }

    public decimal? TotalSpending { get; set; }

    public string Salt { get; set; }

    public string Provider { get; set; }

    public bool ProfileCompleted { get; set; }

    public virtual ICollection<BrowsingHistory> BrowsingHistories { get; set; } = new List<BrowsingHistory>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<GamePoint> GamePoints { get; set; } = new List<GamePoint>();

    public virtual MemberLevel Level { get; set; }

    public virtual ICollection<LoginHistory> LoginHistories { get; set; } = new List<LoginHistory>();

    public virtual ICollection<Oauth> Oauths { get; set; } = new List<Oauth>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();

    public virtual ICollection<PointHistory> PointHistories { get; set; } = new List<PointHistory>();

    public virtual ICollection<ProductReport> ProductReports { get; set; } = new List<ProductReport>();

    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    public virtual ICollection<Record> Records { get; set; } = new List<Record>();

    public virtual ICollection<UserCoupon> UserCoupons { get; set; } = new List<UserCoupon>();

    public virtual ICollection<UserQuestion> UserQuestions { get; set; } = new List<UserQuestion>();

    public virtual ICollection<UsersBlackList> UsersBlackListBlockedBies { get; set; } = new List<UsersBlackList>();

    public virtual ICollection<UsersBlackList> UsersBlackListUsers { get; set; } = new List<UsersBlackList>();
}